/-
  Foundation/CliffordAlgebra.lean
  
  Clifford algebra Cl(3,1) and the Grace operator for FSCTF-BSD.
  The 16-dimensional algebra encodes coherence information.
-/

import Mathlib.Data.Real.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.LinearAlgebra.Basis
import Mathlib.Algebra.BigOperators.Basic

-- Import golden ratio
-- import BSD.Foundation.GoldenRatio

namespace BSD.Foundation.CliffordAlgebra

open BigOperators

/-! # Clifford Algebra Cl(3,1)

The Clifford algebra with signature (+,+,+,-) is a 16-dimensional algebra
generated by γ₁, γ₂, γ₃, γ₄ satisfying γᵢγⱼ + γⱼγᵢ = 2ηᵢⱼ.

Structure:
- Grade 0: 1 element (scalar)
- Grade 1: 4 elements (vectors)
- Grade 2: 6 elements (bivectors)
- Grade 3: 4 elements (trivectors)
- Grade 4: 1 element (pseudoscalar)

Total: 1 + 4 + 6 + 4 + 1 = 16 = 2⁴
-/

/-- The Minkowski signature η = diag(+1,+1,+1,-1) -/
def η (i j : Fin 4) : ℝ :=
  if i = j then
    if i.val < 3 then 1 else -1
  else 0

/-- Verify signature: η(3,3) = -1 -/
lemma eta_33 : η 3 3 = -1 := by simp [η]

/-- Verify signature: η(0,0) = +1 -/
lemma eta_00 : η 0 0 = 1 := by simp [η]

/-! ## Cl(3,1) as a Vector Space

We represent Cl(3,1) by its components in each grade.
-/

/-- An element of Cl(3,1) decomposed by grade -/
structure Cl31 where
  /-- Grade 0: Scalar part (1 component) -/
  scalar : ℝ
  /-- Grade 1: Vector part (4 components, indexed by Fin 4) -/
  vector : Fin 4 → ℝ
  /-- Grade 2: Bivector part (6 components) -/
  bivector : Fin 6 → ℝ
  /-- Grade 3: Trivector part (4 components) -/
  trivector : Fin 4 → ℝ
  /-- Grade 4: Pseudoscalar part (1 component) -/
  pseudoscalar : ℝ

namespace Cl31

/-! ### Basic Operations -/

/-- Zero element -/
def zero : Cl31 where
  scalar := 0
  vector := fun _ => 0
  bivector := fun _ => 0
  trivector := fun _ => 0
  pseudoscalar := 0

/-- One element (scalar 1) -/
def one : Cl31 where
  scalar := 1
  vector := fun _ => 0
  bivector := fun _ => 0
  trivector := fun _ => 0
  pseudoscalar := 0

/-- Addition -/
def add (u v : Cl31) : Cl31 where
  scalar := u.scalar + v.scalar
  vector := fun i => u.vector i + v.vector i
  bivector := fun i => u.bivector i + v.bivector i
  trivector := fun i => u.trivector i + v.trivector i
  pseudoscalar := u.pseudoscalar + v.pseudoscalar

/-- Negation -/
def neg (u : Cl31) : Cl31 where
  scalar := -u.scalar
  vector := fun i => -u.vector i
  bivector := fun i => -u.bivector i
  trivector := fun i => -u.trivector i
  pseudoscalar := -u.pseudoscalar

/-- Scalar multiplication -/
def smul (c : ℝ) (u : Cl31) : Cl31 where
  scalar := c * u.scalar
  vector := fun i => c * u.vector i
  bivector := fun i => c * u.bivector i
  trivector := fun i => c * u.trivector i
  pseudoscalar := c * u.pseudoscalar

instance : Zero Cl31 := ⟨zero⟩
instance : One Cl31 := ⟨one⟩
instance : Add Cl31 := ⟨add⟩
instance : Neg Cl31 := ⟨neg⟩
instance : SMul ℝ Cl31 := ⟨smul⟩

/-! ### Basis Elements -/

/-- Grade-1 basis element eᵢ for i ∈ Fin 4 -/
def e (i : Fin 4) : Cl31 where
  scalar := 0
  vector := fun j => if i = j then 1 else 0
  bivector := fun _ => 0
  trivector := fun _ => 0
  pseudoscalar := 0

/-- Shorthand for e₁ (first vector basis) -/
def e1 : Cl31 := e 0

/-- Shorthand for e₂ -/
def e2 : Cl31 := e 1

/-- Shorthand for e₃ -/
def e3 : Cl31 := e 2

/-- Shorthand for e₄ (timelike) -/
def e4 : Cl31 := e 3

/-- Grade-2 basis element eᵢⱼ -/
def e_bivec (idx : Fin 6) : Cl31 where
  scalar := 0
  vector := fun _ => 0
  bivector := fun j => if idx = j then 1 else 0
  trivector := fun _ => 0
  pseudoscalar := 0

/-- e₁₂ = e₁ ∧ e₂ (first bivector) -/
def e12 : Cl31 := e_bivec 0

/-! ### Inner Product -/

/-- The Clifford inner product ⟨u,v⟩ = scalar part of ũv
    For our purposes, this is the sum of products of corresponding components.
-/
def innerProduct (u v : Cl31) : ℝ :=
  u.scalar * v.scalar +
  (Finset.univ.sum fun i : Fin 4 => u.vector i * v.vector i) +
  (Finset.univ.sum fun i : Fin 6 => u.bivector i * v.bivector i) +
  (Finset.univ.sum fun i : Fin 4 => u.trivector i * v.trivector i) +
  u.pseudoscalar * v.pseudoscalar

notation "⟨" u ", " v "⟩" => innerProduct u v

/-- Inner product is symmetric -/
theorem inner_symmetric (u v : Cl31) : ⟨u, v⟩ = ⟨v, u⟩ := by
  unfold innerProduct
  ring_nf
  congr 1
  · ring
  congr 1
  · apply Finset.sum_congr rfl; intro i _; ring
  congr 1
  · apply Finset.sum_congr rfl; intro i _; ring
  congr 1
  · apply Finset.sum_congr rfl; intro i _; ring
  · ring

/-- Inner product is bilinear (left linearity) -/
theorem inner_add_left (u v w : Cl31) : ⟨add u v, w⟩ = ⟨u, w⟩ + ⟨v, w⟩ := by
  unfold innerProduct add
  simp only
  ring_nf
  congr 1
  · ring
  congr 1
  · rw [← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl; intro i _; ring
  congr 1
  · rw [← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl; intro i _; ring
  congr 1
  · rw [← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl; intro i _; ring
  · ring

/-- Inner product is positive semi-definite -/
theorem inner_nonneg (u : Cl31) : ⟨u, u⟩ ≥ 0 := by
  unfold innerProduct
  apply add_nonneg
  apply add_nonneg
  apply add_nonneg
  apply add_nonneg
  · exact sq_nonneg u.scalar
  · exact Finset.sum_nonneg (fun i _ => sq_nonneg (u.vector i))
  · exact Finset.sum_nonneg (fun i _ => sq_nonneg (u.bivector i))
  · exact Finset.sum_nonneg (fun i _ => sq_nonneg (u.trivector i))
  · exact sq_nonneg u.pseudoscalar

/-- The norm squared -/
def normSq (u : Cl31) : ℝ := ⟨u, u⟩

/-- The norm -/
noncomputable def norm (u : Cl31) : ℝ := Real.sqrt (normSq u)

/-- Norm is non-negative -/
theorem norm_nonneg (u : Cl31) : norm u ≥ 0 := Real.sqrt_nonneg _

/-! ### Grade Projections -/

/-- Project to grade 0 (scalar) -/
def proj0 (u : Cl31) : Cl31 where
  scalar := u.scalar
  vector := fun _ => 0
  bivector := fun _ => 0
  trivector := fun _ => 0
  pseudoscalar := 0

/-- Project to grade 1 (vector) -/
def proj1 (u : Cl31) : Cl31 where
  scalar := 0
  vector := u.vector
  bivector := fun _ => 0
  trivector := fun _ => 0
  pseudoscalar := 0

/-- Project to grade 2 (bivector) -/
def proj2 (u : Cl31) : Cl31 where
  scalar := 0
  vector := fun _ => 0
  bivector := u.bivector
  trivector := fun _ => 0
  pseudoscalar := 0

/-- Project to grade 3 (trivector) -/
def proj3 (u : Cl31) : Cl31 where
  scalar := 0
  vector := fun _ => 0
  bivector := fun _ => 0
  trivector := u.trivector
  pseudoscalar := 0

/-- Project to grade 4 (pseudoscalar) -/
def proj4 (u : Cl31) : Cl31 where
  scalar := 0
  vector := fun _ => 0
  bivector := fun _ => 0
  trivector := fun _ => 0
  pseudoscalar := u.pseudoscalar

/-- Projections are idempotent: Πₖ² = Πₖ -/
theorem proj0_idempotent (u : Cl31) : proj0 (proj0 u) = proj0 u := by
  unfold proj0; rfl

theorem proj1_idempotent (u : Cl31) : proj1 (proj1 u) = proj1 u := by
  unfold proj1; rfl

theorem proj2_idempotent (u : Cl31) : proj2 (proj2 u) = proj2 u := by
  unfold proj2; rfl

theorem proj3_idempotent (u : Cl31) : proj3 (proj3 u) = proj3 u := by
  unfold proj3; rfl

theorem proj4_idempotent (u : Cl31) : proj4 (proj4 u) = proj4 u := by
  unfold proj4; rfl

/-- Projections are complete: Σₖ Πₖ = id -/
theorem proj_complete (u : Cl31) : 
    add (add (add (add (proj0 u) (proj1 u)) (proj2 u)) (proj3 u)) (proj4 u) = u := by
  unfold add proj0 proj1 proj2 proj3 proj4
  simp only
  constructor
  · simp [add_zero]
  constructor
  · ext i; simp [add_zero]
  constructor
  · ext i; simp [add_zero]
  constructor
  · ext i; simp [add_zero]
  · simp [add_zero]

/-- Grade orthogonality: ⟨Πⱼu, Πₖv⟩ = 0 for j ≠ k -/
theorem grade_orthogonal_01 (u v : Cl31) : ⟨proj0 u, proj1 v⟩ = 0 := by
  unfold innerProduct proj0 proj1
  simp only
  ring_nf
  simp [Finset.sum_const_zero]

end Cl31

/-! ## The Grace Operator

G = Σₖ φ⁻ᵏ Πₖ

The Grace operator weights each grade by powers of the golden ratio inverse.
This provides natural UV regularization.
-/

/-- The golden ratio (imported from GoldenRatio module) -/
noncomputable def φ : ℝ := (1 + Real.sqrt 5) / 2

/-- φ⁻¹ for convenience -/
noncomputable def φ_inv : ℝ := φ⁻¹

/-- The Grace operator applied to a Cl31 element.
    G(u) = φ⁰·Π₀(u) + φ⁻¹·Π₁(u) + φ⁻²·Π₂(u) + φ⁻³·Π₃(u) + φ⁻⁴·Π₄(u)
-/
noncomputable def grace (u : Cl31) : Cl31 where
  scalar := u.scalar                          -- grade 0: ×1 (= φ⁰)
  vector := fun i => φ_inv * u.vector i       -- grade 1: ×φ⁻¹
  bivector := fun i => φ_inv^2 * u.bivector i -- grade 2: ×φ⁻²
  trivector := fun i => φ_inv^3 * u.trivector i -- grade 3: ×φ⁻³
  pseudoscalar := φ_inv^4 * u.pseudoscalar    -- grade 4: ×φ⁻⁴

notation "𝒢" => grace

/-- Grace-weighted inner product ⟨u,v⟩_G = ⟨G(u),v⟩ -/
noncomputable def graceInnerProduct (u v : Cl31) : ℝ :=
  Cl31.innerProduct (grace u) v

notation "⟨" u ", " v "⟩_G" => graceInnerProduct u v

/-- Grace norm squared -/
noncomputable def graceNormSq (u : Cl31) : ℝ := ⟨u, u⟩_G

/-- Grace norm -/
noncomputable def graceNorm (u : Cl31) : ℝ := Real.sqrt (graceNormSq u)

notation "‖" u "‖_G" => graceNorm u

/-! ### Grace Operator Properties -/

/-- Grace is linear -/
theorem grace_linear (u v : Cl31) (c : ℝ) : 
    grace (Cl31.add (Cl31.smul c u) v) = 
    Cl31.add (Cl31.smul c (grace u)) (grace v) := by
  unfold grace Cl31.add Cl31.smul
  simp only
  constructor
  · ring
  constructor
  · ext i; ring
  constructor
  · ext i; ring
  constructor
  · ext i; ring
  · ring

/-- Grace preserves scalars (grade 0 eigenvalue = 1) -/
theorem grace_scalar (c : ℝ) : 
    grace (Cl31.smul c Cl31.one) = Cl31.smul c Cl31.one := by
  unfold grace Cl31.smul Cl31.one
  simp only
  constructor
  · ring
  constructor
  · ext i; simp; ring
  constructor
  · ext i; simp; ring
  constructor
  · ext i; simp; ring
  · simp; ring

/-- φ > 1 so φ⁻¹ < 1 -/
theorem phi_inv_lt_one : φ_inv < 1 := by
  unfold φ_inv φ
  have h_sqrt5_gt_1 : Real.sqrt 5 > 1 := by
    rw [show (1 : ℝ) = Real.sqrt 1 by norm_num]
    exact Real.sqrt_lt_sqrt (by norm_num) (by norm_num)
  have h_phi_gt_1 : (1 + Real.sqrt 5) / 2 > 1 := by linarith
  rw [inv_lt_one_iff]
  right
  exact h_phi_gt_1

/-- φ⁻¹ is positive -/
theorem phi_inv_pos : φ_inv > 0 := by
  unfold φ_inv φ
  have h_sqrt5_pos : Real.sqrt 5 > 0 := Real.sqrt_pos.mpr (by norm_num)
  have h_phi_pos : (1 + Real.sqrt 5) / 2 > 0 := by linarith
  exact inv_pos.mpr h_phi_pos

/-- Grace contracts higher grades (assuming φ⁻¹ < 1) -/
theorem grace_contracts_vectors (u : Cl31) (hu : u.scalar = 0) 
    (h_biv : ∀ i, u.bivector i = 0) (h_tri : ∀ i, u.trivector i = 0) 
    (h_ps : u.pseudoscalar = 0) :
    graceNormSq u ≤ Cl31.normSq u := by
  -- Grace norm of a pure vector: φ⁻¹ · ||v||²
  -- Since φ⁻¹ < 1, we have graceNormSq ≤ normSq
  unfold graceNormSq graceInnerProduct grace Cl31.innerProduct Cl31.normSq
  simp only [hu, h_biv, h_tri, h_ps, mul_zero, zero_mul, Finset.sum_const_zero, zero_add, add_zero]
  -- Now we have: (Σᵢ (φ⁻¹ * vᵢ) * vᵢ) ≤ (Σᵢ vᵢ * vᵢ)
  -- i.e., φ⁻¹ * Σᵢ vᵢ² ≤ Σᵢ vᵢ²
  have h : (Finset.univ.sum fun i : Fin 4 => φ_inv * u.vector i * u.vector i) = 
           φ_inv * (Finset.univ.sum fun i : Fin 4 => u.vector i * u.vector i) := by
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro i _
    ring
  rw [h]
  have h_sum_nonneg : 0 ≤ Finset.univ.sum fun i : Fin 4 => u.vector i * u.vector i := 
    Finset.sum_nonneg (fun i _ => mul_self_nonneg _)
  calc φ_inv * (Finset.univ.sum fun i => u.vector i * u.vector i) 
      ≤ 1 * (Finset.univ.sum fun i => u.vector i * u.vector i) := by
        apply mul_le_mul_of_nonneg_right (le_of_lt phi_inv_lt_one) h_sum_nonneg
    _ = Finset.univ.sum fun i => u.vector i * u.vector i := by ring

/-- Grace is idempotent on scalars -/
theorem grace_idempotent_scalar (u : Cl31) 
    (hv : ∀ i, u.vector i = 0) (hb : ∀ i, u.bivector i = 0)
    (ht : ∀ i, u.trivector i = 0) (hp : u.pseudoscalar = 0) :
    grace (grace u) = grace u := by
  unfold grace
  simp only
  constructor
  · rfl
  all_goals {
    ext i
    simp [hv, hb, ht, hp]
    ring
  }

end BSD.Foundation.CliffordAlgebra
