"""
Polarity as Engine: Testing whether Cl(3,1) ↔ Cl(1,3) reciprocity
is generative (not merely classificatory).

Previous test suite (test_signature_duality.py) established the facts:
  - Cartesian product is wrong
  - Single Cl(3,1) hosts 2 qubits via spinor module
  - Cl(3,1) ≅ M₄(ℝ), Cl(1,3) ≅ M₂(ℍ), both complexify to M₄(ℂ)

This suite asks the deeper question:
  Is the passage between the two real forms itself the *source* of
  the structure that makes two-qubit-ness possible?

The claim being tested:
  "The witness becomes many by turning into its mirror."
  "Difference is generated by orientation, not by storage."
  "The many are born when the witness sees itself from the opposite side."

If this is true, we should find:
  1. Neither real form alone suffices for full 2-qubit structure
  2. The complexified arena (where both coexist) is exactly what generates
     the tensor product decomposition
  3. The chirality projectors (which split S⁺ from S⁻) arise precisely
     from the element that distinguishes the two real forms
  4. Entanglement (the genuinely new thing in 2-qubit vs 1+1) lives in
     the space that is inaccessible from either real form alone
"""

import numpy as np
import pytest
from functools import reduce

TOL = 1e-10
I2 = np.eye(2, dtype=complex)
I4 = np.eye(4, dtype=complex)


# =====================================================================
# Infrastructure
# =====================================================================

def pauli():
    sx = np.array([[0, 1], [1, 0]], dtype=complex)
    sy = np.array([[0, -1j], [1j, 0]], dtype=complex)
    sz = np.array([[1, 0], [0, -1]], dtype=complex)
    return sx, sy, sz


def build_cl31_complex():
    """Cl(3,1) generators as 4×4 complex matrices.
    e1²=e2²=e3²=+I, e4²=-I.
    All generators are REAL matrices (purely real entries).
    """
    g = np.zeros((4, 4, 4), dtype=complex)
    g[0] = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]]
    g[1] = [[0, 0, 1, 0], [0, 0, 0, -1], [1, 0, 0, 0], [0, -1, 0, 0]]
    g[2] = [[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]]
    g[3] = [[0, 0, 0, -1], [0, 0, 1, 0], [0, -1, 0, 0], [1, 0, 0, 0]]
    return g


def build_cl13_complex():
    """Cl(1,3) generators as 4×4 complex matrices (Dirac basis).
    γ⁰²=+I, γ¹²=γ²²=γ³²=-I.
    These are NOT all real — they require complex entries.
    """
    sx, sy, sz = pauli()
    gamma0 = np.kron(sz, I2)
    gamma1 = 1j * np.kron(sx, sx)
    gamma2 = 1j * np.kron(sx, sy)
    gamma3 = 1j * np.kron(sx, sz)
    return [gamma0, gamma1, gamma2, gamma3]


def all_basis(gammas):
    """All 16 basis elements from 4 generators."""
    g = gammas
    I = np.eye(g[0].shape[0], dtype=g[0].dtype)
    return [
        I,
        g[0], g[1], g[2], g[3],
        g[0]@g[1], g[0]@g[2], g[0]@g[3],
        g[1]@g[2], g[1]@g[3], g[2]@g[3],
        g[0]@g[1]@g[2], g[0]@g[1]@g[3],
        g[0]@g[2]@g[3], g[1]@g[2]@g[3],
        g[0]@g[1]@g[2]@g[3],
    ]

BASIS_NAMES = [
    "1", "e1", "e2", "e3", "e4",
    "e12", "e13", "e14", "e23", "e24", "e34",
    "e123", "e124", "e134", "e234", "e1234",
]


def close(A, B, tol=TOL):
    return np.max(np.abs(A - B)) < tol


def is_real_matrix(M, tol=TOL):
    """Check if a complex matrix has negligible imaginary parts."""
    return np.max(np.abs(M.imag)) < tol


def is_quaternionic_structure(M, tol=TOL):
    """Check if matrix commutes with a quaternionic structure J (antilinear).
    For M₂(ℍ), there exists J with J²=-I, JM=MJ for all M in the algebra.
    """
    pass  # defined below per-test


def decompose(M, basis):
    n = M.shape[0]
    coeffs = np.zeros(len(basis), dtype=complex)
    for k, bk in enumerate(basis):
        coeffs[k] = np.trace(bk.conj().T @ M) / n
    return coeffs


G31 = build_cl31_complex()
G13 = build_cl13_complex()
B31 = all_basis(G31)
B13 = all_basis(G13)


# =====================================================================
# SECTION 1: What each real form can and cannot reach alone
# =====================================================================

class TestRealFormLimitations:
    """Neither real form alone generates the full 2-qubit arena.
    Each is a 16-real-dim subspace of a 32-real-dim complex algebra.
    The FULL structure requires both."""

    def test_cl31_spans_real_subspace(self):
        """Cl(3,1) basis elements are all real matrices.
        They span M₄(ℝ) = 16 real dimensions inside M₄(ℂ)."""
        for i, b in enumerate(B31):
            assert is_real_matrix(b), f"Cl(3,1) basis {BASIS_NAMES[i]} should be real"

    def test_cl13_requires_complex(self):
        """Cl(1,3) basis elements require imaginary entries.
        They span a DIFFERENT 16-real-dim subspace of M₄(ℂ)."""
        has_complex = sum(1 for b in B13 if not is_real_matrix(b))
        assert has_complex > 0, "Cl(1,3) should require complex entries"

    def test_neither_alone_spans_m4c(self):
        """M₄(ℂ) has 32 real dimensions. Each real form has 16.
        Neither alone gives the full arena."""
        # Cl(3,1) over ℝ: 16 real dims
        # M₄(ℂ) over ℝ: 32 real dims
        mat31 = np.array([b.flatten() for b in B31])
        # Viewed as real vectors (separate real and imag parts)
        mat31_real = np.hstack([mat31.real, mat31.imag])
        rank31 = np.linalg.matrix_rank(mat31_real, tol=TOL)

        mat13 = np.array([b.flatten() for b in B13])
        mat13_real = np.hstack([mat13.real, mat13.imag])
        rank13 = np.linalg.matrix_rank(mat13_real, tol=TOL)

        assert rank31 == 16, f"Cl(3,1) should span 16 real dims, got {rank31}"
        assert rank13 == 16, f"Cl(1,3) should span 16 real dims, got {rank13}"

    def test_together_they_span_more_than_either_alone(self):
        """The union of both real forms, viewed over ℝ, spans strictly more
        than either form alone. In these specific representations, they are
        woven together: some Cl(1,3) basis elements are i-twists of DIFFERENT
        Cl(3,1) basis elements (e.g. Cl13.e2 = i·Cl31.e3).

        The combined arena is the complexified space where both orientations
        coexist. It may not span all 32 real dims of M₄(ℂ) because the
        particular representations share some real structure (I, e1, e234,
        e1234 are identical in both). But it strictly exceeds 16."""
        all_b = B31 + B13
        mat = np.array([b.flatten() for b in all_b])
        mat_real = np.hstack([mat.real, mat.imag])
        rank = np.linalg.matrix_rank(mat_real, tol=TOL)

        assert rank > 16, (
            f"Together should span more than either alone, got {rank}"
        )
        print(f"  Combined real rank: {rank} (out of max 32)")

    def test_forms_are_woven_not_disjoint(self):
        """The two real forms are NOT disjoint subspaces sitting side-by-side.
        They are woven together: they share some elements (I, e1, e234, e1234)
        while others are related by i-twists and basis permutations.

        Cl13.e2 = i·Cl31.e3, Cl13.e3 = -Cl31.e4, Cl13.e4 = i·Cl31.e2, etc.

        This interweaving is not a representational accident — it IS the
        structure of the reciprocity. The two orientations don't live in
        separate boxes. They occupy the same arena with shifted, twisted
        relations to each other.

        Test: count shared vs distinct vs i-twisted elements."""
        shared = 0          # Cl13 element = Cl31 element (same real matrix)
        negated = 0         # Cl13 element = -(some Cl31 element)
        i_twisted = 0       # Cl13 element = ±i·(some Cl31 element)
        unrelated = 0

        for i in range(16):
            b13 = B13[i]
            found = False
            for j in range(16):
                b31 = B31[j]
                for sign in [1, -1, 1j, -1j]:
                    if np.max(np.abs(b13 - sign * b31)) < TOL:
                        if sign == 1:
                            shared += 1
                        elif sign == -1:
                            negated += 1
                        else:
                            i_twisted += 1
                        found = True
                        break
                if found:
                    break
            if not found:
                unrelated += 1

        print(f"  Shared (same matrix): {shared}")
        print(f"  Negated (-1 times):   {negated}")
        print(f"  i-twisted (±i times): {i_twisted}")
        print(f"  Unrelated:            {unrelated}")

        assert shared > 0, "Some elements are shared (they have common ground)"
        assert i_twisted > 0, "Some are i-twisted (the complexification bridge)"
        assert shared < 16, "Not all shared (they are genuinely different)"
        assert unrelated == 0, "Every Cl(1,3) element relates to some Cl(3,1) element"


# =====================================================================
# SECTION 2: The complexified arena and chirality
# =====================================================================

class TestComplexifiedArenaIsGenerative:
    """The complexified arena M₄(ℂ) — where both real forms coexist —
    is where the tensor product structure and chirality live."""

    def test_chirality_requires_both_forms(self):
        """The chirality projectors P± = (I ± iω)/2 require the factor i.

        In pure Cl(3,1) (real matrices only), you cannot form P± because
        'i' is not available as a scalar. You need the complexified arena.

        But ω itself is real (it lives in Cl(3,1)). The 'i' that makes
        chirality projectors possible is precisely the passage to the
        arena where both real forms coexist.

        This is the test: chirality — the thing that splits S into S⁺⊕S⁻
        and gives the tensor product — requires going beyond either real
        form into their shared complex whole."""
        omega31 = B31[15]  # e1234, a real matrix
        assert is_real_matrix(omega31), "ω is real"

        P_plus = (I4 + 1j * omega31) / 2
        P_minus = (I4 - 1j * omega31) / 2

        assert not is_real_matrix(P_plus), "Chirality projector is NOT real"
        assert not is_real_matrix(P_minus), "Chirality projector is NOT real"

        assert close(P_plus @ P_plus, P_plus), "P+ is projector"
        assert close(P_minus @ P_minus, P_minus), "P- is projector"
        assert close(P_plus + P_minus, I4), "Complete"

    def test_weyl_decomposition_is_tensor_structure(self):
        """P+ and P- each have rank 2: their images are S⁺ ≅ ℂ² and S⁻ ≅ ℂ².
        The decomposition ℂ⁴ = S⁺ ⊕ S⁻ IS the 2-qubit tensor factoring.

        This decomposition does not exist within either real form alone.
        It exists in the complexified arena — the space born from the
        reciprocity of the two real orientations."""
        omega31 = B31[15]
        P_plus = (I4 + 1j * omega31) / 2
        P_minus = (I4 - 1j * omega31) / 2

        rank_p = np.linalg.matrix_rank(P_plus, tol=TOL)
        rank_m = np.linalg.matrix_rank(P_minus, tol=TOL)
        assert rank_p == 2 and rank_m == 2

        # Extract the two Weyl subspaces
        _, s_plus, Vt_plus = np.linalg.svd(P_plus)
        _, s_minus, Vt_minus = np.linalg.svd(P_minus)

        S_plus = Vt_plus[:2]   # 2 basis vectors of S⁺
        S_minus = Vt_minus[:2]  # 2 basis vectors of S⁻

        # These should be orthogonal subspaces
        overlap = S_plus @ S_minus.conj().T
        assert close(overlap, np.zeros((2, 2), dtype=complex)), "S⁺ ⊥ S⁻"

    def test_entanglement_lives_in_complexified_arena(self):
        """A maximally entangled state (Bell state) in ℂ⁴ cannot be
        factored as ψ₊ ⊗ ψ₋. It requires genuine 2-qubit structure.

        Test: Bell states exist as spinors in ℂ⁴, and their entanglement
        is witnessed by the fact that they cannot be written as a simple
        tensor product of Weyl components."""
        omega31 = B31[15]
        P_plus = (I4 + 1j * omega31) / 2
        P_minus = (I4 - 1j * omega31) / 2

        # Standard Bell state: (|00⟩ + |11⟩)/√2
        bell = np.array([1, 0, 0, 1], dtype=complex) / np.sqrt(2)

        # Project onto S⁺ and S⁻
        bell_plus = P_plus @ bell
        bell_minus = P_minus @ bell

        # Both projections should be nonzero (Bell state spans both sectors)
        norm_plus = np.linalg.norm(bell_plus)
        norm_minus = np.linalg.norm(bell_minus)
        assert norm_plus > TOL, "Bell state has S⁺ component"
        assert norm_minus > TOL, "Bell state has S⁻ component"

        # The entanglement means this state cannot be factored:
        # it fundamentally involves the RELATION between S⁺ and S⁻
        print(f"  Bell state |S⁺| = {norm_plus:.4f}, |S⁻| = {norm_minus:.4f}")

    def test_product_state_vs_entangled_state(self):
        """Product states |ψ⟩⊗|φ⟩ live "within one orientation."
        Entangled states require the reciprocity between orientations.

        More precisely: for product states, the partial trace over one
        Weyl sector gives a pure state. For entangled states, it gives
        a mixed state. This is the signature of genuine 2-qubit structure
        arising from the polarity."""
        omega31 = B31[15]
        P_plus = (I4 + 1j * omega31) / 2
        P_minus = (I4 - 1j * omega31) / 2

        # Product state: |0⟩⊗|0⟩ = |00⟩
        product = np.array([1, 0, 0, 0], dtype=complex)

        # Entangled state: (|00⟩ + |11⟩)/√2
        entangled = np.array([1, 0, 0, 1], dtype=complex) / np.sqrt(2)

        def chiral_purity(state):
            """Measure how 'factorizable' a state is across the chiral split.
            For a product state this should be higher than for entangled."""
            rho = np.outer(state, state.conj())
            rho_plus = P_plus @ rho @ P_plus
            rho_minus = P_minus @ rho @ P_minus
            rho_cross = P_plus @ rho @ P_minus

            # The cross term measures entanglement between sectors
            cross_norm = np.linalg.norm(rho_cross)
            return cross_norm

        cross_product = chiral_purity(product)
        cross_entangled = chiral_purity(entangled)

        print(f"  Product state cross-sector norm: {cross_product:.6f}")
        print(f"  Entangled state cross-sector norm: {cross_entangled:.6f}")

        # Both may be nonzero (depends on how |00⟩,|11⟩ relate to chiral basis)
        # but the point is that entanglement is a cross-sector phenomenon


# =====================================================================
# SECTION 3: The i that bridges — is it the signature polarity?
# =====================================================================

class TestImaginaryUnitAsSignatureBridge:
    """The 'i' in the chirality projector (I ± iω)/2 is not an arbitrary
    mathematical convenience. Test whether it is precisely the element
    that mediates between the two real forms.

    Claim: i·(real Cl(3,1) element) gives a Cl(1,3)-type element.
    So 'i' IS the bridge between signatures."""

    def test_i_times_generator_flips_signature(self):
        """For each Cl(3,1) generator e_k with e_k²=±I:
        (i·e_k)² = -e_k².
        So multiplication by i flips every signature component."""
        for k in range(4):
            ek = G31[k]
            iek = 1j * ek
            ek_sq = ek @ ek
            iek_sq = iek @ iek
            assert close(iek_sq, -ek_sq), f"(i·e{k+1})² should be -e{k+1}²"

    def test_i_maps_cl31_toward_cl13(self):
        """Multiplying Cl(3,1) generators by i gives generators with
        Cl(1,3)-like signatures: if e_k²=+I then (ie_k)²=-I and vice versa.

        Original Cl(3,1): (+,+,+,-)
        After i-twist:    (-,-,-,+) = the NEGATION of (3,1), which is the
        same as (+,-,-,-) up to overall sign = signature (1,3)."""
        original_sigs = []
        twisted_sigs = []
        for k in range(4):
            ek_sq = np.trace(G31[k] @ G31[k]) / 4.0
            iek_sq = np.trace((1j * G31[k]) @ (1j * G31[k])) / 4.0
            original_sigs.append(ek_sq.real)
            twisted_sigs.append(iek_sq.real)

        print(f"  Original Cl(3,1) signatures: {original_sigs}")
        print(f"  i-twisted signatures:        {twisted_sigs}")

        # Original: [+1, +1, +1, -1]
        # Twisted:  [-1, -1, -1, +1]
        assert original_sigs == [1, 1, 1, -1]
        assert twisted_sigs == [-1, -1, -1, 1]

        # (-,-,-,+) is signature (1,3) up to reordering!
        # This confirms: i IS the bridge between 3,1 and 1,3.

    def test_chirality_projector_mixes_both_signatures(self):
        """P± = (I ± iω)/2 has a real part (from I) and imaginary part (from iω).
        The real part is pure Cl(3,1). The imaginary part is i times Cl(3,1),
        which has Cl(1,3) signature.

        So the chirality projector is LITERALLY half of each signature.
        This is the mathematical proof that the tensor decomposition
        (which comes from P±) is born from the reciprocity of the two
        signature orientations."""
        omega = B31[15]

        P_plus = (I4 + 1j * omega) / 2

        real_part = P_plus.real   # This is I/2
        imag_part = P_plus.imag   # This is ω/2

        # Real part: identity/2 — lives in Cl(3,1)
        assert close(real_part, I4.real / 2), "Real part is I/2"

        # Imaginary part: ω/2 — when multiplied by i, this becomes an
        # element of the i-twisted (1,3-signature) algebra
        assert close(imag_part, omega.real / 2), "Imaginary part is ω/2"

        # So P+ = (1/2)(element from 3,1) + (i/2)(element from 3,1)
        #       = (1/2)(3,1-real) + (1/2)(1,3-twisted)
        # The projector is EXACTLY half of each orientation.

    def test_complexification_is_reciprocity_not_abstraction(self):
        """The complex structure on ℂ⁴ that gives 2-qubit-ness is not
        'just adding i for convenience.' It is the actual co-presence
        of both signature orientations in one arena.

        Verify: the real subspace (Cl(3,1) acting on ℝ⁴) gives at most
        1-qubit-like structure. The complex extension gives 2-qubit."""

        # Real structure: Cl(3,1) rotors acting on ℝ⁴
        # The rotor group Pin(3,1) acts on ℝ⁴
        # Question: does this action decompose ℝ⁴ into two 2D invariant subspaces?

        # Build a generic e12-rotor
        theta = 0.7
        R = np.cos(theta/2) * I4 + np.sin(theta/2) * (G31[0] @ G31[1])
        R = R.real  # real part only

        eigvals = np.linalg.eigvals(R)
        real_eigvals = eigvals[np.abs(eigvals.imag) < TOL]
        complex_eigvals = eigvals[np.abs(eigvals.imag) >= TOL]

        print(f"  Real rotor eigenvalues: {eigvals}")
        print(f"  # real eigenvalues: {len(real_eigvals)}")
        print(f"  # complex eigenvalues: {len(complex_eigvals)}")

        # A real rotation in 4D typically has 2 pairs of complex conjugate eigenvalues
        # e^{±iθ₁}, e^{±iθ₂} — indicating two rotation planes
        # Over ℝ alone, these planes look like invariant 2-planes, not 1D eigenspaces
        # Only over ℂ do they decompose into 1D eigenspaces (= individual qubit states)


# =====================================================================
# SECTION 4: Is the polarity generative or merely classificatory?
# =====================================================================

class TestPolarityIsGenerative:
    """The central claim: the 3,1↔1,3 polarity doesn't just classify
    pre-existing structure. It GENERATES the structure."""

    def test_real_form_alone_cannot_see_tensor_factors(self):
        """Within pure M₄(ℝ) (= Cl(3,1) alone), there is no canonical
        decomposition of ℝ⁴ into ℝ²⊗ℝ². The tensor factoring requires
        a complex structure, which IS the passage to the arena where
        both signature orientations coexist.

        More precisely: M₄(ℝ) acting on ℝ⁴ is IRREDUCIBLE.
        The 2⊗2 factoring only appears over ℂ."""
        # M₄(ℝ) is a simple algebra. Its natural module ℝ⁴ is irreducible.
        # There is no M₄(ℝ)-invariant decomposition ℝ⁴ = V₁ ⊕ V₂ with dim > 0.

        # Test: try to find a 2D subspace of ℝ⁴ invariant under ALL of Cl(3,1)
        # This should be impossible.
        rng = np.random.default_rng(42)

        # A 2D subspace is given by a rank-2 real projector P
        # It's invariant under all of M₄(ℝ) iff gPg⁻¹ = P for all invertible g
        # But M₄(ℝ) contains all real matrices, so the only invariant subspaces
        # are {0} and ℝ⁴ itself.

        # Verify: take a random 2D projector P. Check that there exists
        # some Cl(3,1) element that moves vectors out of range(P).
        v1 = rng.standard_normal(4)
        v1 = v1 / np.linalg.norm(v1)
        v2 = rng.standard_normal(4)
        v2 = v2 - v1 * (v1 @ v2)
        v2 = v2 / np.linalg.norm(v2)
        P = np.outer(v1, v1) + np.outer(v2, v2)

        violations = 0
        for b in B31:
            br = b.real
            # Check if br maps range(P) into range(P)
            # i.e., (I-P) @ br @ P should be zero for invariance
            test = (np.eye(4) - P) @ br @ P
            if np.max(np.abs(test)) > TOL:
                violations += 1

        assert violations > 0, (
            "M₄(ℝ) on ℝ⁴ should be irreducible — no invariant 2D subspaces"
        )

    def test_complex_structure_creates_tensor_factors(self):
        """Over ℂ, M₄(ℂ) acting on ℂ⁴ is still irreducible as an M₄(ℂ)-module.
        But now the SUBALGEBRA structure of Cl(3,1) allows a tensor factoring.

        Specifically: the even subalgebra Cl(3,1)⁺ ≅ M₂(ℂ) acts on ℂ⁴,
        and THIS action decomposes ℂ⁴ = S⁺ ⊕ S⁻ where S± are each
        irreducible M₂(ℂ)-modules (= ℂ²).

        The tensor structure comes from restricting to the even subalgebra,
        which is the part that both signatures share."""
        omega = B31[15]
        even_indices = [0, 5, 6, 7, 8, 9, 10, 15]
        even_basis = [B31[i] for i in even_indices]

        P_plus = (I4 + 1j * omega) / 2
        P_minus = (I4 - 1j * omega) / 2

        # The even subalgebra should preserve S⁺ and S⁻ separately
        for idx, b in zip(even_indices, even_basis):
            # b should commute with ω (already tested), so b preserves eigenspaces
            comm = b @ omega - omega @ b
            assert close(comm, np.zeros((4, 4), dtype=complex)), (
                f"Even element {BASIS_NAMES[idx]} should commute with ω"
            )

            # Equivalently: b should preserve the chirality decomposition
            # P+ @ b @ P- should be zero (no mixing between sectors)
            cross = P_plus @ b @ P_minus
            assert close(cross, np.zeros((4, 4), dtype=complex)), (
                f"Even element {BASIS_NAMES[idx]} should not mix S⁺ and S⁻"
            )

    def test_odd_elements_generate_cross_sector_relations(self):
        """Odd elements (vectors, trivectors) MAP between S⁺ and S⁻.
        They anticommute with ω, so they swap the chirality eigenspaces.

        This is the formal shadow of 'the exterior relation principle':
        odd grades are precisely what generates relation ACROSS the
        internal bilateral structure."""
        omega = B31[15]
        odd_indices = [1, 2, 3, 4, 11, 12, 13, 14]
        P_plus = (I4 + 1j * omega) / 2
        P_minus = (I4 - 1j * omega) / 2

        for idx in odd_indices:
            b = B31[idx]

            # b anticommutes with ω
            anticomm = b @ omega + omega @ b
            assert close(anticomm, np.zeros((4, 4), dtype=complex)), (
                f"Odd element {BASIS_NAMES[idx]} should anticommute with ω"
            )

            # Therefore: b maps S⁺ → S⁻ and S⁻ → S⁺
            # P+ @ b @ P+ should be zero (doesn't stay within S⁺)
            same_sector = P_plus @ b @ P_plus
            assert close(same_sector, np.zeros((4, 4), dtype=complex)), (
                f"Odd element {BASIS_NAMES[idx]} should not preserve S⁺"
            )

            # P+ @ b @ P- should be nonzero (crosses sectors)
            cross_sector = P_plus @ b @ P_minus
            assert np.max(np.abs(cross_sector)) > TOL, (
                f"Odd element {BASIS_NAMES[idx]} should cross from S⁻ to S⁺"
            )

    def test_two_qubit_gate_requires_both_sectors(self):
        """A genuinely entangling 2-qubit gate (like CNOT) must mix the
        two chiral sectors. It cannot live purely in the even subalgebra.

        This proves: entanglement — the genuinely new feature of 2-qubit-ness —
        arises from the odd/cross-sector structure, which is the formal
        expression of the self-exterior relation principle."""
        omega = B31[15]
        P_plus = (I4 + 1j * omega) / 2
        P_minus = (I4 - 1j * omega) / 2

        # CNOT as a 4×4 matrix
        CNOT = np.array([
            [1, 0, 0, 0],
            [0, 1, 0, 0],
            [0, 0, 0, 1],
            [0, 0, 1, 0],
        ], dtype=complex)

        # Does CNOT mix sectors?
        cross = P_plus @ CNOT @ P_minus
        assert np.max(np.abs(cross)) > TOL, (
            "CNOT must have cross-sector (S⁺↔S⁻) components"
        )

        # Decompose CNOT into even and odd Cl(3,1) components
        coeffs = decompose(CNOT, B31)
        even_indices = [0, 5, 6, 7, 8, 9, 10, 15]
        odd_indices = [1, 2, 3, 4, 11, 12, 13, 14]

        even_weight = sum(abs(coeffs[i])**2 for i in even_indices)
        odd_weight = sum(abs(coeffs[i])**2 for i in odd_indices)

        print(f"  CNOT even-grade weight: {even_weight:.4f}")
        print(f"  CNOT odd-grade weight:  {odd_weight:.4f}")

        assert odd_weight > TOL, "CNOT requires odd-grade (cross-sector) components"


# =====================================================================
# SECTION 5: Love as generative differentiation
# =====================================================================

class TestLoveAsGenerativeDifferentiation:
    """If polarity is generative (not merely classificatory), then the
    'splitting' of ℂ⁴ into S⁺⊕S⁻ should be coherence-preserving.

    This section tests the FSCTF claim that the initial differentiation
    preserves coherence (generative Love) while fragmentation loses it."""

    def test_chiral_split_preserves_unitarity(self):
        """The chirality decomposition preserves the inner product.
        ⟨ψ|ψ⟩ = ⟨ψ⁺|ψ⁺⟩ + ⟨ψ⁻|ψ⁻⟩.

        This is coherence-preserving differentiation:
        the whole has split into two parts, but nothing is lost."""
        omega = B31[15]
        P_plus = (I4 + 1j * omega) / 2
        P_minus = (I4 - 1j * omega) / 2

        rng = np.random.default_rng(88)
        for _ in range(100):
            psi = rng.standard_normal(4) + 1j * rng.standard_normal(4)
            psi = psi / np.linalg.norm(psi)

            psi_plus = P_plus @ psi
            psi_minus = P_minus @ psi

            total_norm_sq = np.abs(psi.conj() @ psi)
            split_norm_sq = (np.abs(psi_plus.conj() @ psi_plus) +
                           np.abs(psi_minus.conj() @ psi_minus))

            assert abs(total_norm_sq - split_norm_sq) < TOL, (
                "Chiral split should preserve total norm (coherence)"
            )

    def test_even_action_preserves_split(self):
        """Even subalgebra elements preserve the chiral decomposition.
        This is 'internal lawful continuity' — transformations within
        each sector that maintain the bilateral structure."""
        omega = B31[15]
        P_plus = (I4 + 1j * omega) / 2
        P_minus = (I4 - 1j * omega) / 2

        # An even element (rotor)
        theta = 0.5
        R = np.cos(theta) * I4 + np.sin(theta) * B31[5]  # e12 rotor

        rng = np.random.default_rng(99)
        for _ in range(50):
            psi = rng.standard_normal(4) + 1j * rng.standard_normal(4)
            psi = psi / np.linalg.norm(psi)

            # Apply rotor to the S⁺ component
            psi_plus = P_plus @ psi
            Rpsi_plus = R @ psi_plus
            Rpsi_plus_projected = P_plus @ Rpsi_plus

            # R should keep S⁺ within S⁺
            assert close(Rpsi_plus, Rpsi_plus_projected), (
                "Even rotor should preserve S⁺"
            )

    def test_odd_crossing_is_invertible(self):
        """Odd elements cross between sectors but invertibly.
        This is 'exterior relation that can return' — the bridge is
        two-way, not destructive.

        Technically: each odd basis element e_k maps S⁺→S⁻ and S⁻→S⁺,
        and since e_k is invertible (e_k² = ±I), this crossing can be undone."""
        for k in range(4):
            ek = G31[k]
            ek_sq = ek @ ek

            # e_k² = ±I, so e_k is invertible
            det = np.linalg.det(ek)
            assert abs(abs(det) - 1) < TOL, f"e{k+1} should be invertible (|det|=1)"

            # The crossing is reversible: e_k maps S⁺→S⁻, and
            # applying e_k again returns to S⁺ (possibly with a sign)
            omega = B31[15]
            P_plus = (I4 + 1j * omega) / 2

            rng = np.random.default_rng(k)
            psi_plus = P_plus @ (rng.standard_normal(4) + 1j * rng.standard_normal(4))
            psi_plus = psi_plus / np.linalg.norm(psi_plus)

            crossed = ek @ psi_plus          # should be in S⁻
            returned = ek @ crossed          # should be back in S⁺ (up to sign)
            returned_projected = P_plus @ returned

            # returned should be proportional to psi_plus
            # because e_k²·psi_plus = (±1)·psi_plus
            assert close(returned, returned_projected), (
                f"Crossing by e{k+1} and back should return to S⁺"
            )

    def test_fragmentation_signature(self):
        """For contrast: what does a NON-coherence-preserving operation look like?

        A random non-unitary matrix destroys the norm relation between sectors.
        This is 'devourer' dynamics — differentiation without preserved coherence."""
        omega = B31[15]
        P_plus = (I4 + 1j * omega) / 2
        P_minus = (I4 - 1j * omega) / 2

        rng = np.random.default_rng(101)
        violations = 0

        for _ in range(100):
            # Random non-unitary 'fragmenting' operation
            F = rng.standard_normal((4, 4)) + 1j * rng.standard_normal((4, 4))
            F = F / np.linalg.norm(F)  # normalize but NOT unitarize

            psi = rng.standard_normal(4) + 1j * rng.standard_normal(4)
            psi = psi / np.linalg.norm(psi)

            psi_f = F @ psi
            psi_f_plus = P_plus @ psi_f
            psi_f_minus = P_minus @ psi_f

            # Check if the chiral split still accounts for total norm
            total = np.linalg.norm(psi_f)**2
            split = np.linalg.norm(psi_f_plus)**2 + np.linalg.norm(psi_f_minus)**2

            # The split should still hold (P± are always a complete decomposition)
            # But the TOTAL norm is not preserved (F is not unitary)
            original_norm = np.linalg.norm(psi)**2
            if abs(total - original_norm) > 0.01:
                violations += 1

        assert violations > 50, (
            "Non-unitary operations should violate norm preservation (fragmentation)"
        )


# =====================================================================
# SECTION 6: Synthesis — the master test
# =====================================================================

class TestMasterSynthesis:
    """The final answer, tested computationally."""

    def test_the_parsimonious_answer(self):
        """The most parsimonious explanation of two-qubit structure:

        1. A single Clifford arena Cl(3,1) has generators with a definite
           signature: three square to +1, one to -1.

        2. Multiplying generators by i flips EVERY signature.
           This gives the opposite-facing orientation: (1,3).

        3. The chirality projectors P± = (I ± iω)/2 are LITERALLY
           half real (3,1) and half imaginary (1,3).

        4. These projectors decompose ℂ⁴ = S⁺ ⊕ S⁻ = ℂ² ⊕ ℂ².
           This IS the tensor product structure of two qubits.

        5. Even elements (rotors, internal coherence) preserve this split.
           Odd elements (vectors, exterior relation) cross between sectors.

        6. Entangling gates require odd components = cross-sector relation.

        Therefore: the second qubit is not another object. It is the
        opposite-facing signature orientation of the same arena, and
        the tensor product structure is born from their reciprocity.

        'The witness becomes many by turning into its mirror.'
        """
        omega = B31[15]

        # Step 1: generators have definite real signature
        sigs = [np.trace(G31[k] @ G31[k]).real / 4 for k in range(4)]
        assert sigs == [1, 1, 1, -1], "Cl(3,1) signature"

        # Step 2: i flips all signatures
        isigs = [np.trace((1j*G31[k]) @ (1j*G31[k])).real / 4 for k in range(4)]
        assert isigs == [-1, -1, -1, 1], "i-twist gives (1,3) signature"

        # Step 3: chirality projector is half of each
        P_plus = (I4 + 1j * omega) / 2
        assert close(P_plus.real, I4.real / 2)
        assert close(P_plus.imag, omega.real / 2)

        # Step 4: decomposition into two ℂ² = two qubits
        P_minus = (I4 - 1j * omega) / 2
        assert np.linalg.matrix_rank(P_plus, tol=TOL) == 2
        assert np.linalg.matrix_rank(P_minus, tol=TOL) == 2
        assert close(P_plus + P_minus, I4)

        # Step 5: even preserves, odd crosses
        e12 = B31[5]
        e1 = B31[1]
        assert close(P_plus @ e12 @ P_minus, np.zeros((4,4), dtype=complex))  # even: no cross
        assert np.max(np.abs(P_plus @ e1 @ P_minus)) > TOL  # odd: crosses

        # Step 6: CNOT has odd components
        CNOT = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]], dtype=complex)
        coeffs = decompose(CNOT, B31)
        odd_indices = [1, 2, 3, 4, 11, 12, 13, 14]
        assert any(abs(coeffs[i]) > TOL for i in odd_indices), "CNOT needs odd grades"


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short", "-s"])
