/-
  ZX/Basic.lean
  
  ZX-Calculus Core Data Types
  
  ZX-calculus is a graphical language for quantum computation where:
  - Green (Z) spiders represent Z-basis operations
  - Red (X) spiders represent X-basis operations  
  - Wires represent qubits
  - Composition is vertical stacking, tensor is horizontal juxtaposition
  
  This module defines the core syntax of ZX diagrams as an inductive type.
-/

import Mathlib.Data.Real.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Data.Fin.Basic

namespace ZXClifford.ZX

/-! ## Phase Type -/

/-- A phase is an angle in [0, 2π), typically a multiple of π/4 for Clifford -/
abbrev Phase := ℝ

/-- Common phases -/
def Phase.zero : Phase := 0
noncomputable def Phase.pi : Phase := Real.pi
noncomputable def Phase.halfPi : Phase := Real.pi / 2
noncomputable def Phase.quarterPi : Phase := Real.pi / 4

/-! ## Spider Color -/

/-- The two colors of ZX spiders -/
inductive SpiderColor
  | Z  -- Green spider (Z basis)
  | X  -- Red spider (X basis)
deriving DecidableEq, Repr

namespace SpiderColor

/-- Swap colors (for color change rule) -/
def swap : SpiderColor → SpiderColor
  | Z => X
  | X => Z

theorem swap_involutive : ∀ c, swap (swap c) = c := by
  intro c; cases c <;> rfl

end SpiderColor

/-! ## ZX Diagram Type -/

/-- 
  A ZX diagram with m inputs and n outputs.
  
  This is the free dagger-compact category generated by Z and X spiders.
  
  The type indices ensure diagrams compose correctly:
  - `ZXDiagram m n` has m input wires and n output wires
  - Composition `D₁ ; D₂` requires D₁ : m → n and D₂ : n → p
  - Tensor `D₁ ⊗ D₂` creates D₁ ⊗ D₂ : (m₁+m₂) → (n₁+n₂)
-/
inductive ZXDiagram : Nat → Nat → Type
  /-- Identity on n wires -/
  | id : (n : Nat) → ZXDiagram n n
  
  /-- Z spider with k inputs, l outputs, and phase α -/
  | zSpider : (k l : Nat) → (phase : Phase) → ZXDiagram k l
  
  /-- X spider with k inputs, l outputs, and phase α -/
  | xSpider : (k l : Nat) → (phase : Phase) → ZXDiagram k l
  
  /-- Hadamard gate (1 input, 1 output) -/
  | hadamard : ZXDiagram 1 1
  
  /-- Wire swap (2 inputs, 2 outputs) -/
  | swap : ZXDiagram 2 2
  
  /-- Cup (Bell state creation): 0 inputs, 2 outputs -/
  | cup : ZXDiagram 0 2
  
  /-- Cap (Bell state measurement): 2 inputs, 0 outputs -/
  | cap : ZXDiagram 2 0
  
  /-- Sequential composition: D₁ ; D₂ -/
  | compose : {m n p : Nat} → ZXDiagram m n → ZXDiagram n p → ZXDiagram m p
  
  /-- Parallel composition (tensor): D₁ ⊗ D₂ -/
  | tensor : {m₁ n₁ m₂ n₂ : Nat} → 
             ZXDiagram m₁ n₁ → ZXDiagram m₂ n₂ → ZXDiagram (m₁ + m₂) (n₁ + n₂)

namespace ZXDiagram

/-! ### Notation -/

/-- Composition notation -/
scoped infixl:60 " ⬝ " => ZXDiagram.compose

/-- Tensor notation -/
scoped infixl:70 " ⊗ " => ZXDiagram.tensor

/-! ### Basic Constructors -/

/-- Empty diagram (0 wires) -/
def empty : ZXDiagram 0 0 := id 0

/-- Single wire -/
def wire : ZXDiagram 1 1 := id 1

/-- Z spider with no phase (copy/delete operations) -/
def zSpider0 (k l : Nat) : ZXDiagram k l := zSpider k l 0

/-- X spider with no phase -/
def xSpider0 (k l : Nat) : ZXDiagram k l := xSpider k l 0

/-- Z phase gate (1 input, 1 output) -/
def zPhase (α : Phase) : ZXDiagram 1 1 := zSpider 1 1 α

/-- X phase gate (1 input, 1 output) -/
def xPhase (α : Phase) : ZXDiagram 1 1 := xSpider 1 1 α

/-- Z rotation by π (Pauli Z) -/
noncomputable def pauliZ : ZXDiagram 1 1 := zPhase Phase.pi

/-- X rotation by π (Pauli X) -/
noncomputable def pauliX : ZXDiagram 1 1 := xPhase Phase.pi

/-- S gate (Z rotation by π/2) -/
noncomputable def sGate : ZXDiagram 1 1 := zPhase Phase.halfPi

/-- T gate (Z rotation by π/4) -/
noncomputable def tGate : ZXDiagram 1 1 := zPhase Phase.quarterPi

/-- CNOT gate using ZX decomposition -/
def cnot : ZXDiagram 2 2 :=
  -- CNOT = (id ⊗ X-spider) ; (Z-spider ⊗ id)
  -- More precisely: control-Z-spider and target-X-spider
  (id 1 ⊗ xSpider0 1 2) ⬝ (zSpider0 2 1 ⊗ id 1)

/-- CZ gate (Control-Z via ZX decomposition) -/
def cz : ZXDiagram 2 2 :=
  -- CZ = (id ⊗ H) ; CNOT ; (id ⊗ H)
  -- Simplified: direct Z-spider interaction
  zSpider0 2 2

/-! ### Dagger (Adjoint) Operation -/

/-- The dagger (adjoint) of a diagram: flip inputs/outputs, negate phases -/
def dagger : {m n : Nat} → ZXDiagram m n → ZXDiagram n m
  | _, _, id n => id n
  | _, _, zSpider k l α => zSpider l k (-α)
  | _, _, xSpider k l α => xSpider l k (-α)
  | _, _, hadamard => hadamard
  | _, _, swap => swap
  | _, _, cup => cap
  | _, _, cap => cup
  | _, _, compose D₁ D₂ => compose (dagger D₂) (dagger D₁)
  | _, _, tensor D₁ D₂ => tensor (dagger D₁) (dagger D₂)

/-- Dagger notation -/
postfix:max "†" => dagger

/-- Dagger is involutive -/
theorem dagger_involutive : ∀ {m n : Nat} (D : ZXDiagram m n), D†† = D := by
  intro m n D
  induction D with
  | id n => rfl
  | zSpider k l α => simp [dagger, neg_neg]
  | xSpider k l α => simp [dagger, neg_neg]
  | hadamard => rfl
  | swap => rfl
  | cup => rfl
  | cap => rfl
  | compose D₁ D₂ ih₁ ih₂ => simp [dagger, ih₁, ih₂]
  | tensor D₁ D₂ ih₁ ih₂ => simp [dagger, ih₁, ih₂]

/-! ### Wire Count Operations -/

/-- Number of input wires -/
def inputs : {m n : Nat} → ZXDiagram m n → Nat
  | m, _, _ => m

/-- Number of output wires -/  
def outputs : {m n : Nat} → ZXDiagram m n → Nat
  | _, n, _ => n

/-! ### Spider Operations -/

/-- Get the color of a spider generator (None for non-spiders) -/
def spiderColor? : {m n : Nat} → ZXDiagram m n → Option SpiderColor
  | _, _, zSpider _ _ _ => some .Z
  | _, _, xSpider _ _ _ => some .X
  | _, _, _ => none

/-- Get the phase of a spider generator (0 for non-spiders) -/
def spiderPhase : {m n : Nat} → ZXDiagram m n → Phase
  | _, _, zSpider _ _ α => α
  | _, _, xSpider _ _ α => α
  | _, _, _ => 0

/-! ### Diagram Size (for termination proofs) -/

/-- Size of a diagram (number of generators) -/
def size : {m n : Nat} → ZXDiagram m n → Nat
  | _, _, id _ => 1
  | _, _, zSpider _ _ _ => 1
  | _, _, xSpider _ _ _ => 1
  | _, _, hadamard => 1
  | _, _, swap => 1
  | _, _, cup => 1
  | _, _, cap => 1
  | _, _, compose D₁ D₂ => size D₁ + size D₂
  | _, _, tensor D₁ D₂ => size D₁ + size D₂

theorem size_pos : ∀ {m n : Nat} (D : ZXDiagram m n), 0 < size D := by
  intro m n D
  induction D <;> simp [size] <;> omega

end ZXDiagram

/-! ## Standard ZX Generators -/

/-- The standard ZX generators as a sum type -/
inductive ZXGenerator
  | zSpider (k l : Nat) (phase : Phase)
  | xSpider (k l : Nat) (phase : Phase)
  | hadamard
  | swap
  | cup
  | cap

namespace ZXGenerator

/-- Convert generator to diagram -/
def toDiagram : ZXGenerator → (Σ m n, ZXDiagram m n)
  | zSpider k l α => ⟨k, l, ZXDiagram.zSpider k l α⟩
  | xSpider k l α => ⟨k, l, ZXDiagram.xSpider k l α⟩
  | hadamard => ⟨1, 1, ZXDiagram.hadamard⟩
  | swap => ⟨2, 2, ZXDiagram.swap⟩
  | cup => ⟨0, 2, ZXDiagram.cup⟩
  | cap => ⟨2, 0, ZXDiagram.cap⟩

/-- Input arity of a generator -/
def inputArity : ZXGenerator → Nat
  | zSpider k _ _ => k
  | xSpider k _ _ => k
  | hadamard => 1
  | swap => 2
  | cup => 0
  | cap => 2

/-- Output arity of a generator -/
def outputArity : ZXGenerator → Nat
  | zSpider _ l _ => l
  | xSpider _ l _ => l
  | hadamard => 1
  | swap => 2
  | cup => 2
  | cap => 0

end ZXGenerator

end ZXClifford.ZX
